#!/bin/bash

if [ "$0" = "$BASH_SOURCE" ]
then
   echo -e "\e[1;36m[\e[1;34m!\e[1;36m] To completely wipe the system, invoke using \e[1;35m'source .naomi/scripts/naomi-purge'"
   exit 1
fi

echo -e "\e[1;36m[\e[1;31m!\e[1;36m] \e[1;31mThis will completely reset your Naomi install.  \e[1;36mAre you sure you want to do this?"
echo
echo -n -e "\e[1;36mChoice [\e[1;35mY\e[1;36m/\e[1;35mN\e[1;36m]: \e[0m"

read -N1 -s key
case $key in
   [Yy])
      echo $key
      echo -e "\e[1;36m[\e[1;34m!\e[1;36m] Starting wipe in 2 seconds...\e[0m"
      echo ""
      sleep 2
      echo -e "\e[1;36m[\e[1;34m!\e[1;36m] Wiping system...\e[0m"

      # Remove all Naomi user settings
      echo
      echo -e "\e[1;32mRemoving Configs...\e[0m"
      sudo rm -Rf ~/.naomi/configs

      # Wipe network settings
      echo
      echo -e "\e[1;32mWiping Network Settings...\e[0m"
      if [ -f /etc/wpa_supplicant/wpa_supplicant.conf ]
      then
         sudo rm /etc/wpa_supplicant/wpa_supplicant.conf
      fi
      echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev" | sudo tee -a /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null
      echo "update_config=1" | sudo tee -a /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null
      echo "country=US" | sudo tee -a /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null

      # wipe ssh keys. A new one will be regenerated
      # in the auto_run.sh script on first boot.
      echo
      echo -e "\e[1;32mWiping SSH Keys...\e[0m"
      sudo rm /etc/ssh/ssh_host_*

      # Reset to run setup next boot
      echo
      echo -e "\e[1;32mActivating First Run Condition...\e[0m"
      touch ~/first_run

      # Reset bash history
      echo
      echo -e "\e[1;32mClearing Bash History...\e[0m"
      history -c
      history -w

      # Done
      echo
      echo -e "\e[1;36m[\e[1;34m!\e[1;36m] Wipe is complete.  Shutting down in 5 seconds.\e[0m"
      sleep 5
      sudo shutdown now
      ;;

   *)
      echo $key
      echo ""
      echo -e "\e[1;31mAborting Wipe."
      ;;
esac
